# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TravisTesting' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TravisTesting

  target 'TravisTestingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TravisTestingUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
